"""Generate a synthetic candidate population via the Claude CLI (Phase 11).

Mirrors seed_jobs.py: a deterministic, weighted spec grid (archetype x role family
x level) is fleshed out by the headless Claude CLI into realistic CandidateProfileV2
records, normalized (provenance + completeness), and frozen as a committed seed.
The DB seeds these into the `profiles` table so every module (Profile, Match,
Pipeline) shows an enterprise-like load instead of one personal CV.

    python -m pipeline.jobfit.seed_candidates --count 50 --workers 4
    python -m pipeline.jobfit.seed_candidates --limit 3   # quick validation
"""

from __future__ import annotations

import argparse
import json
import random
import sys
import time
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
from typing import Any

from ._summary import format_distribution
from .claude_cli import ClaudeCliError, ClaudeCliProvider
from .profile import CandidateProfileV2, normalize_profile

ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = ROOT / "data" / "seed_candidates" / "candidates.json"

FAMILIES = ("software_engineering", "data_ai", "product_project")
ARCHETYPES = ("bau", "student", "career_switcher")

# The bank's NON-TECH families, activated by the round-4 taxonomy skill graph. The
# tech slice (cand-000..049) is generated by build_specs(); this fixed slice
# (cand-050..) gives matching a real non-tech candidate pool so the non-tech JOBS
# have someone to match. ``target`` seeds aspirations + the targetRole key
# seed_analyses reads; ``skills`` are phrased to land on phase-1 taxonomy terms.
CSAS_NONTECH_ROLES: list[dict[str, Any]] = [
    # --- finance_accounting ---
    {"family": "finance_accounting", "archetype": "bau", "target": "Credit Risk Analyst",
     "skills": ["credit analysis", "credit scoring", "underwriting", "IFRS 9", "financial analysis"]},
    {"family": "finance_accounting", "archetype": "bau", "target": "Účetní (Accountant)",
     "skills": ["účetnictví", "general ledger", "accounts payable", "bank reconciliation", "financial reporting"]},
    {"family": "finance_accounting", "archetype": "bau", "target": "AML / Compliance Analyst",
     "skills": ["AML", "KYC", "transaction monitoring", "sanctions screening", "customer due diligence"]},
    {"family": "finance_accounting", "archetype": "student", "target": "Junior Controlling Specialist",
     "skills": ["controlling", "budgeting", "financial analysis", "financial modeling", "Excel"]},
    # --- operations_logistics ---
    {"family": "operations_logistics", "archetype": "bau", "target": "Loan Administration Specialist",
     "skills": ["document management", "records management", "standard operating procedures", "data entry", "process improvement"]},
    {"family": "operations_logistics", "archetype": "bau", "target": "Operational Excellence Specialist",
     "skills": ["process improvement", "lean management", "six sigma", "standard operating procedures", "kaizen"]},
    {"family": "operations_logistics", "archetype": "career_switcher", "target": "Payments Back-Office Specialist",
     "skills": ["order processing", "data entry", "document management", "process documentation", "quality control"]},
    {"family": "operations_logistics", "archetype": "student", "target": "Junior Procurement Specialist",
     "skills": ["procurement", "purchasing", "supplier management", "invoicing", "negotiation"]},
    # --- sales_marketing ---
    {"family": "sales_marketing", "archetype": "bau", "target": "Corporate Relationship Banker",
     "skills": ["account management", "relationship building", "B2B sales", "cross-selling", "negotiation"]},
    {"family": "sales_marketing", "archetype": "bau", "target": "Personal Banker",
     "skills": ["customer acquisition", "upselling", "relationship building", "sales", "account management"]},
    {"family": "sales_marketing", "archetype": "career_switcher", "target": "Digital Marketing Specialist",
     "skills": ["digital marketing", "SEO", "PPC", "social media marketing", "content marketing"]},
    {"family": "sales_marketing", "archetype": "student", "target": "Junior Business Development",
     "skills": ["lead generation", "business development", "cold calling", "market research", "sales reporting"]},
    # --- customer_support ---
    {"family": "customer_support", "archetype": "bau", "target": "Complaints Specialist",
     "skills": ["reklamace", "complaint resolution", "escalation management", "conflict resolution", "SLA management"]},
    {"family": "customer_support", "archetype": "bau", "target": "Client Service Specialist",
     "skills": ["account servicing", "customer onboarding", "back office support", "email support", "knowledge base"]},
    {"family": "customer_support", "archetype": "career_switcher", "target": "Customer Retention Specialist",
     "skills": ["customer retention", "customer success", "CSAT", "NPS", "customer feedback"]},
    {"family": "customer_support", "archetype": "student", "target": "Contact Center Specialist",
     "skills": ["customer service", "inbound calls", "call handling", "ticketing", "complaint resolution"]},
]

# The non-tech candidate slice starts here so its ids never collide with the tech
# slice (cand-000..049); build_nontech_specs stamps cand-050..
_NONTECH_ID_START = 50

# Independent LLM calls keep defaulting to the same few common Czech names, so we
# STAMP a guaranteed-unique name onto every candidate (like seed_jobs stamps the
# controlled dimensions). Gendered first names pair with gendered surnames.
_FEMALE_FIRST = (
    "Tereza", "Markéta", "Kristýna", "Lucie", "Klára", "Adéla", "Veronika", "Eliška",
    "Barbora", "Kateřina", "Anna", "Jana", "Petra", "Hana", "Zuzana", "Nikola",
    "Michaela", "Aneta", "Karolína", "Denisa", "Simona", "Gabriela", "Monika", "Lenka",
)
_MALE_FIRST = (
    "Tomáš", "Vojtěch", "Ondřej", "Jakub", "Jan", "Petr", "Martin", "Lukáš",
    "David", "Filip", "Marek", "Pavel", "Jiří", "Michal", "Adam", "Štěpán",
    "Daniel", "Matěj", "Roman", "Tadeáš", "Vít", "Radek", "Dominik", "Patrik",
)
# Masculine base form; the feminine form is derived below.
_SURNAMES = (
    "Novák", "Svoboda", "Novotný", "Dvořák", "Černý", "Procházka", "Kučera", "Veselý",
    "Horák", "Němec", "Pokorný", "Pospíšil", "Hájek", "Jelínek", "Král", "Růžička",
    "Beneš", "Fiala", "Sedláček", "Zeman", "Kolář", "Navrátil", "Čermák", "Vaněk",
    "Urban", "Blažek", "Kříž", "Kovář", "Bartoš", "Vlček", "Polák", "Konečný",
    "Mareš", "Šimek", "Tichý", "Bureš", "Sýkora", "Malý", "Holub", "Beránek",
)


# Softening map for the "fleeting -ě-" surnames (Vaněk -> Vaňková): dropping the
# ě leaves the preceding consonant soft, which Czech spells with a háček.
_SOFTEN = {"n": "ň", "t": "ť", "d": "ď"}


def _feminize(surname: str) -> str:
    """Masculine Czech surname -> feminine form.

    Novák->Nováková, Černý->Černá, Svoboda->Svobodová — and the FLEETING-E class,
    where the final -e- of ``-ek``/``-ec``/``-ěk`` drops before the suffix:
    Hájek->Hájková, Němec->Němcová, Vaněk->Vaňková. Naively appending -ová there
    minted forms that do not exist in Czech (``Hájeková``, ``Němecová``) — 10 of
    the 66 shipped seed candidates carried one, on a corpus demoed to a Czech bank.

    Known limitation: the fleeting-e rule is regular for the curated ``_SURNAMES``
    pool but has lexical exceptions elsewhere (Švec->Ševcová); adding such a name
    to the pool needs its own case here.
    """
    if surname.endswith(("ý", "í")):
        return surname[:-1] + "á"
    if surname.endswith("a"):
        return surname[:-1] + "ová"
    # -ěk: drop the ě and soften the consonant it palatalized (Vaněk -> Vaňková).
    if len(surname) > 2 and surname.endswith("ěk"):
        stem, prev = surname[:-3], surname[-3]
        return stem + _SOFTEN.get(prev.lower(), prev) + "ková"
    # -ek / -ec: the e is fleeting (Hájek -> Hájková, Němec -> Němcová).
    if len(surname) > 2 and surname.endswith(("ek", "ec")):
        return surname[:-2] + surname[-1] + "ová"
    return surname + "ová"


def _base_name_pool() -> list[str]:
    """Every distinct gender-consistent full name mint-able from the curated pools.

    Female first names pair with feminized surnames, male first names with the
    masculine base form, so the two halves never collide.
    """
    pool = [f"{first} {_feminize(s)}" for first in _FEMALE_FIRST for s in _SURNAMES]
    pool += [f"{first} {s}" for first in _MALE_FIRST for s in _SURNAMES]
    return pool


def name_pool_capacity() -> int:
    """How many distinct base full names the curated pools can mint (no suffixes)."""
    return (len(_FEMALE_FIRST) + len(_MALE_FIRST)) * len(_SURNAMES)


def unique_czech_names(n: int, *, seed: int = 7) -> list[str]:
    """``n`` deterministic, gender-consistent, UNIQUE Czech full names.

    Always returns EXACTLY ``n`` distinct names. Within the curated pool
    (``name_pool_capacity()`` names) they are randomly sampled for variety;
    beyond it the pool is enumerated exhaustively and any further names degrade
    deterministically to numbered suffixes (e.g. ``"Jan Novák 2"``). This keeps
    callers that index ``names[i]`` or ``zip(records, names)`` from crashing or
    silently truncating when ``n`` approaches/exceeds the pool — the feature's
    enterprise-scale promise should not 2 AM-IndexError mid-run.
    """
    if n <= 0:
        return []
    rng = random.Random(seed)
    used: set[str] = set()
    out: list[str] = []
    base = _base_name_pool()
    capacity = len(base)
    target = min(n, capacity)

    # Phase 1: random sampling within the curated pool. Output is unchanged from
    # prior versions for n <= capacity (same body, same termination on len==n).
    guard = 0
    while len(out) < target and guard < capacity * 200:
        guard += 1
        if rng.random() < 0.5:
            full = f"{rng.choice(_FEMALE_FIRST)} {_feminize(rng.choice(_SURNAMES))}"
        else:
            full = f"{rng.choice(_MALE_FIRST)} {rng.choice(_SURNAMES)}"
        if full not in used:
            used.add(full)
            out.append(full)

    # Phase 2: deterministic top-up if sampling didn't drain the curated pool
    # (coupon-collector tail) — guarantees we reach the full capacity.
    for full in base:
        if len(out) >= target:
            break
        if full not in used:
            used.add(full)
            out.append(full)

    # Phase 3: beyond the curated capacity, degrade with numbered suffixes so the
    # result is still exactly n unique names instead of self-capping short.
    suffix = 2
    while len(out) < n:
        for full in base:
            if len(out) >= n:
                break
            candidate = f"{full} {suffix}"
            if candidate not in used:
                used.add(candidate)
                out.append(candidate)
        suffix += 1
    return out

_SYSTEM = (
    "You invent realistic but fictional Czech tech-job candidates. Use varied Czech names. "
    "Never reuse a real person. Output strict JSON only."
)

# Non-tech bank candidates are a BUSINESS craft, not a tech stack — the CV must
# not list programming languages/frameworks. Their skillClaims/evidence anchor on
# real banking competencies (credit analysis, AML/KYC, reklamace, controlling, …)
# so they resolve against the phase-1 taxonomy and can actually match the non-tech
# bank JOBS in the corpus.
_NONTECH_SYSTEM = (
    "You invent realistic but fictional candidates for BUSINESS roles at a Czech retail bank "
    "(finance, operations, sales, client service) — NOT engineers. Do NOT invent programming "
    "languages or developer tools. Use varied Czech names. Never reuse a real person. Output strict JSON only."
)

_COMMON_KEYS = (
    '"displayName": str, "roleFamily": "{family}", "educationLevel": "phd|master|bachelor|university|unknown",\n'
    '  "educationDetail": str, "languages": [str], "location": str, "aspirations": [str],\n'
    '  "skillClaims": [ {{ "skill": str, "level": "foundational|working|strong", '
    '"provenance": str }} ],\n'
    '  "evidence": [ {{ "kind": str, "title": str, "text": str, "skills": [str], "link": str|null }} ]'
)


def _prompt(spec: dict[str, Any]) -> str:
    if spec.get("nontech"):
        return _nontech_prompt(spec)
    family = spec["family"]
    base = "Generate ONE fictional candidate as a JSON object with keys:\n{\n  " + _COMMON_KEYS.format(family=family) + "\n}\n"
    if spec["archetype"] == "student":
        flavor = (
            f"Profile a STUDENT / recent graduate targeting {family}. No real work history "
            "(at most an off-field part-time job). 4-6 skillClaims with provenance in "
            "coursework/self_declared/academic_project. 2-3 evidence items of kind thesis/project/"
            "course/internship/extracurricular with realistic titles, a short text, and skills; "
            "give projects a 'link'. Include educationDetail (programme + Czech university + year) "
            "and aspirations. Omit seniority/yearsExperience."
        )
    elif spec["archetype"] == "career_switcher":
        flavor = (
            f"Profile a CAREER-SWITCHER moving INTO {family} from a different field. Include "
            "\"yearsExperience\": number (their prior-career years) and 1-2 evidence items of kind "
            "\"job\" describing that PRIOR (non-tech) role, plus 3-5 target-domain skillClaims learned "
            "via coursework/projects and 1-2 project/course evidence items with links. aspirations = target role."
        )
    else:
        flavor = (
            f"Profile an EXPERIENCED {family} professional. Include \"yearsExperience\": number and "
            "\"seniority\": \"junior|medior|senior|lead\" (bias to medior/senior), 5-8 skillClaims with "
            "provenance \"professional\", and 1-2 evidence items of kind \"job\" with employer-style titles and skills."
        )
    return f"{base}\n{flavor}\nReturn JSON only — no markdown, no commentary."


def _nontech_prompt(spec: dict[str, Any]) -> str:
    family = spec["family"]
    target = spec["target"]
    skills = spec["skills"]
    base = "Generate ONE fictional candidate as a JSON object with keys:\n{\n  " + _COMMON_KEYS.format(family=family) + "\n}\n"
    skills_line = (
        f"Anchor the skillClaims/evidence on THESE real banking competencies: {json.dumps(skills, ensure_ascii=False)} "
        "(you may add 1-2 adjacent business skills). Name each skill PLAINLY (the competency itself, e.g. "
        '"credit analysis", "AML", "KYC", "reklamace", "controlling") — never a programming language or dev tool.'
    )
    bilingual = (
        "Write a realistic BILINGUAL Czech CV: mix Czech and English naturally (Czech employer names, "
        "Czech role titles like 'bankovní poradce' / 'specialista', English for skills is fine)."
    )
    if spec["archetype"] == "student":
        flavor = (
            f"Profile a STUDENT / recent graduate targeting a {target} role at a Czech bank. No real work "
            "history (at most an off-field part-time job). 4-6 skillClaims with provenance in "
            "coursework/self_declared/academic_project. 2-3 evidence items of kind thesis/project/course/"
            "internship with realistic titles, a short text and skills. Include educationDetail (a business/"
            "economics programme + Czech university + year) and aspirations. Omit seniority/yearsExperience."
        )
    elif spec["archetype"] == "career_switcher":
        flavor = (
            f"Profile a CAREER-SWITCHER moving INTO a {target} role from a different field. Include "
            "\"yearsExperience\": number (prior-career years) and 1-2 evidence items of kind \"job\" describing "
            "that PRIOR role, plus 3-5 target-domain skillClaims learned via a course/retraining and 1-2 "
            "course/project evidence items. aspirations = the target role."
        )
    else:
        flavor = (
            f"Profile an EXPERIENCED banking professional whose target is {target}. Include \"yearsExperience\": "
            "number and \"seniority\": \"junior|medior|senior|lead\" (bias to medior/senior), 5-8 skillClaims with "
            "provenance \"professional\", and 1-2 evidence items of kind \"job\" with Czech-bank employer titles and skills."
        )
    return f"{base}\n{flavor}\n{skills_line}\n{bilingual}\nReturn JSON only — no markdown, no commentary."


def build_specs(count: int, *, seed: int = 7) -> list[dict[str, Any]]:
    rng = random.Random(seed)
    names = unique_czech_names(count, seed=seed)
    specs: list[dict[str, Any]] = []
    for i in range(count):
        archetype = rng.choices(ARCHETYPES, weights=[40, 40, 20])[0]
        family = rng.choices(FAMILIES, weights=[55, 25, 20])[0]
        specs.append({"id": f"cand-{i:03d}", "archetype": archetype, "family": family, "display_name": names[i]})
    return specs


def build_nontech_specs(*, seed: int = 7) -> list[dict[str, Any]]:
    """The fixed NON-TECH candidate slice (ids cand-050..), one per CSAS_NONTECH_ROLES.

    Names are drawn from the SAME unique pool as the tech slice but from the range
    AFTER it (``[_NONTECH_ID_START:]``), so a non-tech candidate can never collide
    with a tech one no matter how the two are combined.
    """
    n = _NONTECH_ID_START + len(CSAS_NONTECH_ROLES)
    names = unique_czech_names(n, seed=seed)[_NONTECH_ID_START:]
    specs: list[dict[str, Any]] = []
    for j, role in enumerate(CSAS_NONTECH_ROLES):
        specs.append(
            {
                "id": f"cand-{_NONTECH_ID_START + j:03d}",
                "archetype": role["archetype"],
                "family": role["family"],
                "display_name": names[j],
                "nontech": True,
                "target": role["target"],
                "skills": role["skills"],
            }
        )
    return specs


def _gen_one(provider: ClaudeCliProvider, spec: dict[str, Any], *, retries: int, backoff: float):
    last = "unknown"
    system = _NONTECH_SYSTEM if spec.get("nontech") else _SYSTEM
    for attempt in range(retries + 1):
        try:
            raw = provider.complete(_prompt(spec), system=system).json()
            if isinstance(raw, dict):
                profile = CandidateProfileV2.model_validate(raw)
                profile.archetype = spec["archetype"]  # guarantee the distribution
                profile.role_family = spec["family"]
                score, _missing = normalize_profile(profile)  # stamp + reuse the score
                rec = profile.model_dump(by_alias=True, exclude_none=True)
                rec["id"] = spec["id"]
                rec["displayName"] = spec["display_name"]  # stamp the guaranteed-unique name
                rec["completeness"] = score
                if spec.get("target"):
                    # The ČS role this candidate targets — seed_analyses reads targetRole
                    # to score them against the matching role JD (mirrors align_candidates_csas).
                    rec["targetRole"] = spec["target"]
                return rec, None
            last = "not-a-dict"
        except ClaudeCliError as exc:
            last = f"cli:{exc.subtype or 'error'}"
        except ValueError:
            last = "unparseable-json"
        except Exception as exc:  # schema/validation
            last = f"invalid:{type(exc).__name__}"
        if attempt < retries:
            time.sleep(backoff * (attempt + 1))
    return None, last


def generate(
    count: int,
    *,
    workers: int = 4,
    seed: int = 7,
    limit: int | None = None,
    retries: int = 2,
    backoff: float = 3.0,
    existing: dict[str, dict[str, Any]] | None = None,
    provider: ClaudeCliProvider | None = None,
    specs: list[dict[str, Any]] | None = None,
) -> tuple[list[dict[str, Any]], dict[str, int]]:
    provider = provider or ClaudeCliProvider(timeout=180)
    if not provider.available():
        raise SystemExit("Claude CLI not available on PATH.")
    specs = specs if specs is not None else build_specs(count, seed=seed)
    if limit:
        specs = specs[:limit]
    records: dict[str, dict[str, Any]] = dict(existing or {})
    todo = [s for s in specs if s["id"] not in records]
    print(f"Candidates: specs={len(specs)} existing={len(records)} todo={len(todo)} (workers={workers})…", file=sys.stderr)

    failures: Counter[str] = Counter()
    if todo:
        with ThreadPoolExecutor(max_workers=max(1, min(workers, len(todo)))) as pool:
            futures = {pool.submit(_gen_one, provider, s, retries=retries, backoff=backoff): s for s in todo}
            done = 0
            for fut in as_completed(futures):
                rec, err = fut.result()
                done += 1
                if rec:
                    records[rec["id"]] = rec
                else:
                    failures[err or "unknown"] += 1
                if done % 15 == 0:
                    print(f"  …{done}/{len(todo)} attempted, {len(records)} total", file=sys.stderr)

    ordered = [records[k] for k in sorted(records)]
    return ordered, dict(failures)


def _refuse_id_collision(count: int) -> str | None:
    """Message when ``--count`` would let the TECH slice overwrite the NON-TECH one.

    ``build_specs`` numbers cand-000..cand-{count-1}; the fixed bank slice starts at
    cand-050. Above that ceiling the ids overlap, and both ``generate``'s resume
    merge and the final write are keyed on the id — so ``--count 60 --no-resume``
    silently replaces 10 of the 16 non-tech bank candidates with tech ones, while
    the seeded analyses and pipeline entries keep pointing at those ids under their
    old (now wrong) role family. Refuse instead. Returns None when the count is safe.
    """
    if count <= _NONTECH_ID_START:
        return None
    return (
        f"--count {count} exceeds the tech-slice ceiling ({_NONTECH_ID_START}): ids "
        f"cand-{_NONTECH_ID_START:03d}.. belong to the fixed non-tech bank slice "
        "(CSAS_NONTECH_ROLES) and would be overwritten. Raise _NONTECH_ID_START to "
        "grow the tech corpus, or use --nontech to regenerate only the bank slice."
    )


def _warn_if_over_capacity(requested: int) -> None:
    """Tell the operator up front when names will degrade to numbered suffixes."""
    capacity = name_pool_capacity()
    if requested > capacity:
        print(
            f"Note: requested {requested} names exceeds the curated pool ({capacity}); "
            f"the extra {requested - capacity} get deterministic numbered suffixes "
            "(e.g. 'Jan Novák 2').",
            file=sys.stderr,
        )


def summarize(records: list[dict[str, Any]]) -> str:
    arche = Counter(r.get("archetype") for r in records)
    fam = Counter(r.get("roleFamily") for r in records)
    avg_complete = sum(r.get("completeness", 0) for r in records) / max(len(records), 1)
    return "\n".join(
        [
            f"total: {len(records)}",
            format_distribution("archetype", arche),
            format_distribution("role_family", fam),
            f"avg completeness: {avg_complete:.2f}",
        ]
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate the synthetic candidate population.")
    parser.add_argument("--count", type=int, default=50)
    parser.add_argument("--workers", type=int, default=4)
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--retries", type=int, default=2)
    parser.add_argument("--limit", type=int, default=None)
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--no-resume", action="store_true")
    parser.add_argument(
        "--rename-only",
        action="store_true",
        help="Reassign deterministic UNIQUE names to the existing seed (no LLM) and exit. "
        "Profiles are kept; only displayName changes.",
    )
    parser.add_argument(
        "--nontech",
        action="store_true",
        help="Generate ONLY the fixed non-tech bank slice (cand-050..) and MERGE it into the "
        "existing seed, leaving the tech slice untouched. Use this to top up the corpus after "
        "the taxonomy grew non-tech families, without regenerating (and reshuffling) cand-000..049.",
    )
    args = parser.parse_args(argv)

    if args.rename_only:
        if not args.out.exists():
            print(f"No candidate seed at {args.out}", file=sys.stderr)
            return 1
        records = json.loads(args.out.read_text(encoding="utf-8"))
        records.sort(key=lambda r: r.get("id", ""))
        _warn_if_over_capacity(len(records))
        names = unique_czech_names(len(records), seed=args.seed)
        for rec, name in zip(records, names):
            rec["displayName"] = name
        args.out.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")
        distinct = len({r["displayName"] for r in records})
        print(f"Renamed {len(records)} candidates to {distinct} unique names.", file=sys.stderr)
        return 0 if distinct == len(records) else 1

    # --nontech generates ONLY the fixed bank slice, so the tech ceiling doesn't apply.
    if not args.nontech and (refusal := _refuse_id_collision(args.count)):
        print(refusal, file=sys.stderr)
        return 1

    _warn_if_over_capacity(args.count)
    existing: dict[str, dict[str, Any]] = {}
    # --nontech ALWAYS merges into the existing seed (it tops up, never replaces);
    # otherwise resume unless --no-resume was passed.
    if args.out.exists() and (args.nontech or not args.no_resume):
        try:
            for rec in json.loads(args.out.read_text(encoding="utf-8")):
                if isinstance(rec, dict) and rec.get("id"):
                    existing[rec["id"]] = rec
        except (json.JSONDecodeError, OSError):
            pass

    nontech_specs = build_nontech_specs(seed=args.seed) if args.nontech else None
    records, failures = generate(
        args.count, workers=args.workers, seed=args.seed, limit=args.limit,
        retries=args.retries, existing=existing, specs=nontech_specs,
    )
    if not records:
        print("No candidates generated.", file=sys.stderr)
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(json.dumps(records, ensure_ascii=False, indent=2), encoding="utf-8")
    try:
        shown = args.out.relative_to(ROOT)
    except ValueError:
        shown = args.out
    print(f"\nWrote {len(records)} candidates to {shown} (failures: {dict(failures)})", file=sys.stderr)
    print(summarize(records), file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
