// The server-side glyph catalog serves the generated art byte-for-byte.
//
// The 13 traced modules in ./glyphs/ are AUTO-GENERATED by .claude/skills/motionize
// and are never edited; the catalog only changes WHO imports them. So the one thing
// it must never do is serve something other than what the module exports: every id
// maps to the very object its module exports (identity, not a copy), and the ids are
// exactly the registry's vocabulary.
//
//   npm run test:unit
import { test } from "node:test";
import assert from "node:assert/strict";
import { readdirSync } from "node:fs";
import { fileURLToPath, pathToFileURL } from "node:url";
import { GLYPH_CATALOG, glyphArt } from "./glyphCatalog.ts";
import { GLYPH_IDS } from "./glyphRegistry.ts";
import type { TracedGlyph } from "./MotionizedGlyph";

const GLYPHS_DIR = fileURLToPath(new URL("./glyphs/", import.meta.url));

test("the catalog has exactly one entry per GlyphId", () => {
  assert.deepEqual(Object.keys(GLYPH_CATALOG).sort(), [...GLYPH_IDS].sort());
});

test("catalog[id] is the TracedGlyph the matching generated module exports", async () => {
  const files = readdirSync(GLYPHS_DIR).filter((f) => /Glyph\.ts$/.test(f) && !f.includes(".test."));
  assert.equal(files.length, GLYPH_IDS.length);
  for (const file of files) {
    const id = file.replace(/Glyph\.ts$/, "") as (typeof GLYPH_IDS)[number];
    const mod = (await import(pathToFileURL(`${GLYPHS_DIR}${file}`).href)) as Record<string, TracedGlyph>;
    const exported = Object.values(mod);
    assert.equal(exported.length, 1, `${file} should export exactly one glyph`);
    assert.equal(GLYPH_CATALOG[id], exported[0], `${id} is not the object ${file} exports`);
    assert.deepEqual(glyphArt(id), exported[0]);
  }
});

test("glyphArt answers null for an unknown or prototype-key id, never throws", () => {
  assert.equal(glyphArt("nope"), null);
  assert.equal(glyphArt("constructor"), null);
  assert.equal(glyphArt("__proto__"), null);
  assert.equal(glyphArt(""), null);
});
