// Print ONE production interviewer brief — an operator tool for reading exactly what the
// live agent is given for a kind and a role.
//
// The eval harness does NOT call this: pipeline/jobfit/eval/interview_eval.py reads the
// committed snapshot pipeline/jobfit/eval/interview_briefs.json, generated by
// scripts/interview-briefs-snapshot.ts (`npm run interview:briefs`) through the same
// renderKind() this script uses. So this output and the eval's brief come from one render.
//
//   node --import ./scripts/test-alias-loader.mjs --experimental-transform-types \
//     scripts/interview-brief.ts --brief student --role "a junior engineering role"
//
// Prints JSON `{ "brief": "<the brief string>" }` to stdout.
// `--brief` ∈ default | student | case | grounded. `grounded` seeds a fixture entry + prep
// into a THROWAWAY database (never data/kp.sqlite) and renders composeBrief through the real
// buildGroundedInterview; `--role` is then the job title. See
// docs/development/voice-interview-testing.md.

import { mkdtempSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { BRIEF_KINDS, renderKind, type BriefKind } from "./interview-briefs-snapshot.ts";

function arg(name: string): string | undefined {
  const argv = process.argv.slice(2);
  const i = argv.indexOf(`--${name}`);
  return i >= 0 && i + 1 < argv.length ? argv[i + 1] : undefined;
}

const kind = (arg("brief") ?? "default") as BriefKind;
if (!BRIEF_KINDS.includes(kind)) {
  process.stderr.write(`interview-brief: unknown --brief ${kind}; expected one of ${BRIEF_KINDS.join(", ")}\n`);
  process.exit(2);
}
if (kind === "grounded") {
  // Always a throwaway database: the grounded render writes a fixture entry and prep pack.
  process.env.KP_DB_PATH = path.join(mkdtempSync(path.join(tmpdir(), "kp-brief-")), "kp.sqlite");
  process.env.KP_EMPTY = "1";
}
const durationRaw = arg("duration");

const brief = await renderKind(kind, arg("role") ?? "", {
  company: arg("company") ?? null,
  candidateLabel: arg("candidate") ?? null,
  durationMin: durationRaw ? Number(durationRaw) : null,
});

process.stdout.write(JSON.stringify({ brief }));
