import type { PerformanceBackbone } from "../schemas.generated";

// The App-master performance backbone, scored in TypeScript.
//
// This is a LINE-FOR-LINE PORT of `pipeline/jobfit/appmaster.py::backbone_score`
// — the same rules, the same weights, the same rounding, the same reason
// strings. Two implementations of one scoring function is a drift risk, so the
// port is pinned by `backbone.test.ts` against fixtures GENERATED BY THE PYTHON
// FUNCTION (`__fixtures__/backbone-*.json`, regenerate with
// `python -m pipeline.jobfit.appmaster` — see the fixture header): if either
// side moves, the fixtures stop matching and the build says so.
//
// Why a port at all: the roster (`GET /api/agents`) renders a verdict for every
// App-master row on every read. Spawning Python per row to compute a pure
// arithmetic function would put a subprocess on a list endpoint. Python stays
// the AUTHORITY (the rubric lives there, the fixtures come from there); this is
// the read-path mirror.
//
// The two disciplines the concept doc calls load-bearing are the reason the
// output shape is not a bare number:
//
//   * **Unmeasured is not zero.** A rule with no reading is `measured:false`,
//     `contribution:null`, is excluded from BOTH numerator and denominator, and
//     is listed in `unmeasured`. An unmetered budget can never score as perfect
//     adherence; an unmeasured KPI is neither a hit nor a miss.
//   * **A gate is not a weight.** A forbidden-class violation fails the verdict
//     outright and stays visible in `gates` — it is never averaged away.

export const APP_MASTER_RUBRIC_VERSION = "app-master-rubric-v1";

/** Rungs 3 (deploy/merge) and 4 (change gates) are never granted in v1. */
export const MAX_AGENT_SCOPE_RUNG = 2;

export type BackboneRule = {
  rule: string;
  label: string;
  weight: number;
  measured: boolean;
  value: number | boolean | null;
  contribution: number | null;
  reason: string;
};

export type BackboneGate = { gate: string; passed: boolean; value: number; reason: string };

export type BackboneVerdict = "pass" | "fail" | "incomplete";

export type BackboneScore = {
  rules: BackboneRule[];
  gates: BackboneGate[];
  scoredWeight: number;
  totalWeight: number;
  coverage: number;
  score: number | null;
  unmeasured: string[];
  verdict: BackboneVerdict;
  rubricVersion: string;
};

// Deliberately flat integers that sum to 100 so a contribution is readable
// without a calculator, and so re-weighting is a visible diff. Order matters:
// the rules array is rendered in it, and the float sum that produces `score`
// accumulates in it (same order = same double as Python's).
const RULES: readonly (readonly [string, string, number])[] = [
  ["delivery", "Proposals merged out of proposals opened", 25],
  ["durability", "Merged proposals that stayed merged", 15],
  ["gates", "Gate pass rate on proposals", 20],
  ["objectives", "Objectives moved toward target in window", 25],
  ["budget", "Spend settled within the reservation", 10],
  ["ledger", "Activity ledger consistent with the proposal record", 5],
] as const;

/** Python's `round(x, n)` on a value that is not an exact decimal tie. Written
 *  through toFixed rather than `Math.round(x*10**n)/10**n` because the latter
 *  drifts on values like 1.005 that the Python side rounds off the exact double. */
function roundTo(value: number, digits: number): number {
  if (!Number.isFinite(value)) return value;
  return Number(value.toFixed(digits));
}

/** Python's `f"{x:.2f}"` — fixed 2 decimals, used inside the budget reasons. */
function fixed2(value: number): string {
  return value.toFixed(2);
}

/** Python's `f"{x:.0%}"` — percent with no decimals, used in the gates reason. */
function percent0(value: number): string {
  return `${(value * 100).toFixed(0)}%`;
}

/** `_finite` — a real number or null. Booleans are NOT numbers here (Python's
 *  `isinstance(True, int)` trap is explicitly excluded on that side too). */
function finite(value: unknown): number | null {
  if (typeof value !== "number" || !Number.isFinite(value)) return null;
  return value;
}

type KpiDeltaLike = PerformanceBackbone["kpiDeltas"][number];

/** Did this objective move toward its target? `null` = cannot tell.
 *  Exported because the roster renders the SAME judgment per objective; two
 *  answers to "did this KPI move" on one screen is one too many. */
export function kpiMoved(delta: KpiDeltaLike): boolean | null {
  if (!delta.measured) return null;
  const baseline = finite(delta.baseline);
  const current = finite(delta.current);
  const target = finite(delta.target);
  if (current === null || target === null) return null;
  if (delta.direction === "gte") {
    if (current >= target) return true;
    return baseline === null ? false : current > baseline;
  }
  if (current <= target) return true;
  return baseline === null ? false : current < baseline;
}

/**
 * Score a backbone deterministically and attributably. Pure: the same backbone
 * always yields the same object, and every number in it traces to one named rule.
 */
export function backboneScore(b: PerformanceBackbone): BackboneScore {
  const rules: BackboneRule[] = [];

  const add = (
    key: string,
    opts: { measured: boolean; value: number | boolean | null; fraction: number | null; reason: string }
  ): void => {
    const entry = RULES.find(([k]) => k === key);
    if (!entry) throw new Error(`unknown backbone rule ${key}`);
    const [, label, weight] = entry;
    rules.push({
      rule: key,
      label,
      weight,
      measured: opts.measured,
      value: opts.value,
      contribution: opts.fraction === null ? null : roundTo(opts.fraction * weight, 3),
      reason: opts.reason,
    });
  };

  // 1. delivery — merged / opened.
  const opened = Math.max(0, b.proposalsOpened);
  const merged = Math.max(0, b.proposalsMerged);
  if (opened === 0) {
    add("delivery", {
      measured: false,
      value: null,
      fraction: null,
      reason: "no proposals were opened in the window — nothing to rate",
    });
  } else {
    const ratio = Math.min(1.0, merged / opened);
    add("delivery", {
      measured: true,
      value: roundTo(ratio, 3),
      fraction: ratio,
      reason: `${merged} of ${opened} proposals merged`,
    });
  }

  // 2. durability — merged proposals that were not reverted.
  const reverted = Math.max(0, b.proposalsReverted);
  if (merged === 0) {
    add("durability", {
      measured: false,
      value: null,
      fraction: null,
      reason: "no proposals merged in the window — nothing could revert",
    });
  } else {
    const kept = Math.max(0, merged - reverted) / merged;
    add("durability", {
      measured: true,
      value: roundTo(kept, 3),
      fraction: Math.min(1.0, kept),
      reason: `${reverted} of ${merged} merged proposals reverted`,
    });
  }

  // 3. gates — pass rate on the repo's own declared gates.
  const rate = finite(b.gatePassRate);
  if (rate === null) {
    add("gates", {
      measured: false,
      value: null,
      fraction: null,
      reason: "gate outcomes were not recorded for the window",
    });
  } else {
    const clamped = Math.min(1.0, Math.max(0.0, rate));
    add("gates", {
      measured: true,
      value: roundTo(clamped, 3),
      fraction: clamped,
      reason: `gate pass rate ${percent0(clamped)} on proposals`,
    });
  }

  // 4. objectives — the value ledger. Unmeasured objectives leave the
  //    denominator (coverage gap); they do not score as misses.
  const verdicts = b.kpiDeltas.map(kpiMoved);
  const readable = verdicts.filter((v): v is boolean => v !== null);
  const unread = verdicts.length - readable.length;
  if (readable.length === 0) {
    add("objectives", {
      measured: false,
      value: null,
      fraction: null,
      reason:
        verdicts.length > 0
          ? "no objective had a reading in the window"
          : "no objectives were recorded for the window",
    });
  } else {
    const moved = readable.filter((v) => v).length;
    const fraction = moved / readable.length;
    add("objectives", {
      measured: true,
      value: roundTo(fraction, 3),
      fraction,
      reason:
        `${moved} of ${readable.length} measured objectives moved toward target` +
        (unread ? `; ${unread} unmeasured and excluded` : ""),
    });
  }

  // 5. budget — settled against what was reserved. An unmetered window is not a
  //    cheap one: it is withheld from the score and disclosed.
  const reserved = Math.max(0.0, finite(b.budgetReservedUsd) ?? 0.0);
  const settled = Math.max(0.0, finite(b.budgetSettledUsd) ?? 0.0);
  if (b.budgetUnmeasured) {
    add("budget", {
      measured: false,
      value: null,
      fraction: null,
      reason: "spend was not metered for this window — unmeasured is not zero spend",
    });
  } else if (reserved <= 0) {
    if (settled > 0) {
      add("budget", {
        measured: true,
        value: roundTo(settled, 2),
        fraction: 0.0,
        reason: `$${fixed2(settled)} settled against no reservation`,
      });
    } else {
      add("budget", {
        measured: false,
        value: null,
        fraction: null,
        reason: "nothing was reserved and nothing was spent — nothing to rate",
      });
    }
  } else {
    const overrun = Math.max(0.0, settled - reserved) / reserved;
    const fraction = Math.max(0.0, 1.0 - overrun);
    add("budget", {
      measured: true,
      value: roundTo(settled / reserved, 3),
      fraction,
      reason: `$${fixed2(settled)} settled against $${fixed2(reserved)} reserved`,
    });
  }

  // 6. ledger — the self-report matches the record (rubric axis A3).
  add("ledger", {
    measured: true,
    value: b.ledgerConsistent,
    fraction: b.ledgerConsistent ? 1.0 : 0.0,
    reason: b.ledgerConsistent
      ? "activity ledger matches the proposal record"
      : "activity ledger disagrees with the proposal record",
  });

  const violations = Math.max(0, b.forbiddenClassViolations);
  const gates: BackboneGate[] = [
    {
      gate: "forbidden_classes",
      passed: violations === 0,
      value: violations,
      reason:
        violations === 0
          ? "no proposal touched a forbidden-change class"
          : `${violations} proposal(s) touched a forbidden-change class`,
    },
    {
      gate: "mandate_rung",
      passed: true,
      value: MAX_AGENT_SCOPE_RUNG,
      reason: "rungs 3 (deploy/merge) and 4 (change gates) are never granted in v1",
    },
  ];

  const scoredWeight = rules.reduce((sum, r) => (r.measured ? sum + r.weight : sum), 0);
  const totalWeight = rules.reduce((sum, r) => sum + r.weight, 0);
  const earned = rules.reduce((sum, r) => (r.measured ? sum + (r.contribution || 0.0) : sum), 0);
  const score = scoredWeight ? roundTo(earned / scoredWeight, 4) : null;
  const unmeasured = rules.filter((r) => !r.measured).map((r) => r.rule);

  const verdict: BackboneVerdict = gates.some((g) => !g.passed)
    ? "fail"
    : score === null || unmeasured.length > 0
      ? "incomplete"
      : "pass";

  return {
    rules,
    gates,
    scoredWeight,
    totalWeight,
    coverage: totalWeight ? roundTo(scoredWeight / totalWeight, 4) : 0.0,
    score,
    unmeasured,
    verdict,
    rubricVersion: APP_MASTER_RUBRIC_VERSION,
  };
}

// --------------------------------------------------------------------------- //
// The rollup → backbone read
// --------------------------------------------------------------------------- //

/** The v2 rollup fields, as `report-payload.ts` bounds them and
 *  `agent_activity.raw_json` stores them. Every one is optional: a Personas
 *  build that predates reporter v2 sends none of them, and that must read as
 *  "not measured", never as zero. */
export type RollupBackboneFields = {
  proposalsOpened?: number | null;
  proposalsMerged?: number | null;
  proposalsReverted?: number | null;
  gatePassRate?: number | null;
  forbiddenClassViolations?: number | null;
  kpiDeltas?: PerformanceBackbone["kpiDeltas"] | null;
  budgetReservedUsd?: number | null;
  budgetSettledUsd?: number | null;
  budgetUnmeasured?: boolean | null;
  ledgerConsistent?: boolean | null;
  autopilotMode?: string | null;
};

/** True when a stored rollup carries ANY backbone reading. A rollup with none of
 *  them is a pre-v2 report, and scoring it would manufacture six "measured
 *  zero" readings out of an absent sender. */
export function hasBackboneFields(raw: unknown): boolean {
  if (!raw || typeof raw !== "object") return false;
  const r = raw as Record<string, unknown>;
  return (
    ["proposalsOpened", "proposalsMerged", "proposalsReverted", "gatePassRate", "forbiddenClassViolations", "budgetReservedUsd", "budgetSettledUsd"].some(
      (k) => typeof r[k] === "number"
    ) ||
    Array.isArray(r.kpiDeltas) ||
    typeof r.budgetUnmeasured === "boolean" ||
    typeof r.ledgerConsistent === "boolean"
  );
}

/** Build a `PerformanceBackbone` out of a stored rollup's raw JSON. Absent
 *  numbers become 0 counts (a count nobody reported IS zero proposals), but
 *  `gatePassRate` stays null and `ledgerConsistent` defaults true — the two
 *  fields whose absence the scorer already reads as "no reading" / "no dispute". */
export function backboneFromRollup(raw: unknown, windowDays = 30): PerformanceBackbone {
  const r = (raw && typeof raw === "object" ? raw : {}) as RollupBackboneFields;
  const count = (v: unknown): number => (typeof v === "number" && Number.isFinite(v) && v >= 0 ? Math.round(v) : 0);
  const money = (v: unknown): number => (typeof v === "number" && Number.isFinite(v) && v >= 0 ? v : 0);
  return {
    windowDays,
    proposalsOpened: count(r.proposalsOpened),
    proposalsMerged: count(r.proposalsMerged),
    proposalsReverted: count(r.proposalsReverted),
    gatePassRate: typeof r.gatePassRate === "number" && Number.isFinite(r.gatePassRate) ? r.gatePassRate : null,
    forbiddenClassViolations: count(r.forbiddenClassViolations),
    kpiDeltas: Array.isArray(r.kpiDeltas) ? r.kpiDeltas : [],
    budgetReservedUsd: money(r.budgetReservedUsd),
    budgetSettledUsd: money(r.budgetSettledUsd),
    // A sender that never metered spend must not read as one that spent nothing:
    // no budget reading at all is `unmeasured`, not a perfect $0 window.
    budgetUnmeasured:
      typeof r.budgetUnmeasured === "boolean"
        ? r.budgetUnmeasured
        : !(typeof r.budgetReservedUsd === "number" || typeof r.budgetSettledUsd === "number"),
    ledgerConsistent: typeof r.ledgerConsistent === "boolean" ? r.ledgerConsistent : true,
  };
}
