"""The committed demo corpus is PUBLIC data. This is the standing guard on it.

`data/seed_*` ships in every clone and into every self-hosted install. Today it is
clean of contact details and credentials — but nothing held it that way, and the
corpus is REGENERATED by an LLM (`seed_candidates`, `seed_analyses`), so a future
regeneration can invent an email, a phone number, or a link to a real person's
account without anyone noticing in a 5 000-line JSON diff. It already had: 22
evidence links pointed at `https://github.com/<plausible czech handle>` — fictional
candidates, real-looking accounts nobody in this repo owns.

The rules below are what "clean" means, checked against the files as committed:

1. no email addresses outside the RFC 2606 reserved domains;
2. no phone numbers outside the reserved 555-01xx range;
3. no credential shapes (provider keys, tokens, private keys);
4. every external handle in a reserved namespace (`github.com/example-*`,
   `example.invalid`) — enforced at generation time by `sanitize_links`;
5. at least one seeded analysis carries a `cv_hash`, so the content-addressed
   surfaces (History re-run grouping, same-CV linkage, profile lineage/staleness)
   are reachable on demo data instead of being NULL-gated everywhere.
"""

from __future__ import annotations

import json
import re
import unittest
from pathlib import Path

from pipeline.jobfit.seed_candidates import EXAMPLE_HANDLE_PREFIX, sanitize_links

DATA = Path(__file__).resolve().parents[3] / "data"
SEED_FILES = sorted(p for p in DATA.rglob("*.json") if p.parent.name.startswith("seed_") or "seed_" in str(p.parent))

# RFC 2606 / RFC 6761 reserved names — the only domains a fixture may name.
RESERVED_DOMAINS = ("example.com", "example.org", "example.net", "example.invalid", "localhost", "invalid", "test")

EMAIL = re.compile(r"[A-Za-z0-9._%+-]+@([A-Za-z0-9.-]+\.[A-Za-z]{2,})")
# 10+ digits with optional separators — loose on purpose; a false positive is a
# fixture that should not have looked like a phone number anyway.
PHONE = re.compile(r"(?<!\w)(?:\+\d{1,3}[ -]?)?(?:\d[ -]?){9,}\d(?!\w)")
# The NANP range reserved for fiction (555-0100..555-0199).
RESERVED_PHONE = re.compile(r"555[ -]?01\d\d")
CREDENTIAL = re.compile(
    r"(sk-[A-Za-z0-9]{16,}"
    r"|AIza[0-9A-Za-z_\-]{20,}"
    r"|gh[pousr]_[A-Za-z0-9]{20,}"
    r"|xox[baprs]-[A-Za-z0-9-]{10,}"
    r"|AKIA[0-9A-Z]{16}"
    r"|-----BEGIN [A-Z ]*PRIVATE KEY)"
)
HANDLE_URL = re.compile(r"https?://(?:www\.)?(github|gitlab)\.com/([A-Za-z0-9_.\-]+)")
LINKEDIN = re.compile(r"https?://(?:[a-z]{2,3}\.)?linkedin\.com/(?:in|company)/([A-Za-z0-9_.\-]+)")


def _seed_text() -> dict[Path, str]:
    return {p: p.read_text(encoding="utf-8") for p in SEED_FILES}


class SeedCorpusHygieneTest(unittest.TestCase):
    def test_there_is_a_corpus_to_check(self) -> None:
        """A guard that silently checks nothing is worse than no guard."""
        self.assertGreaterEqual(len(SEED_FILES), 5, f"expected the seed corpus under {DATA}")

    def test_no_email_addresses_outside_reserved_domains(self) -> None:
        offenders = []
        for path, text in _seed_text().items():
            for match in EMAIL.finditer(text):
                domain = match.group(1).lower()
                if not any(domain == d or domain.endswith("." + d) for d in RESERVED_DOMAINS):
                    offenders.append(f"{path.name}: {match.group(0)}")
        self.assertEqual(offenders, [], "seed corpus carries email addresses")

    def test_no_phone_numbers_outside_the_reserved_range(self) -> None:
        offenders = []
        for path, text in _seed_text().items():
            for match in PHONE.finditer(text):
                if not RESERVED_PHONE.search(match.group(0)):
                    offenders.append(f"{path.name}: {match.group(0)!r}")
        self.assertEqual(offenders, [], "seed corpus carries phone-shaped numbers")

    def test_no_credential_shapes(self) -> None:
        offenders = [
            f"{path.name}: {match.group(0)[:12]}…"
            for path, text in _seed_text().items()
            for match in CREDENTIAL.finditer(text)
        ]
        self.assertEqual(offenders, [], "seed corpus carries a credential shape")

    def test_every_code_host_handle_is_in_the_reserved_namespace(self) -> None:
        """THE regression: 22 links to real-looking personal GitHub accounts."""
        offenders = [
            f"{path.name}: {host}.com/{handle}"
            for path, text in _seed_text().items()
            for host, handle in HANDLE_URL.findall(text)
            if not handle.startswith(EXAMPLE_HANDLE_PREFIX)
        ]
        self.assertEqual(offenders, [], "seed corpus links to non-reserved code-host handles")

    def test_every_linkedin_handle_is_in_the_reserved_namespace(self) -> None:
        offenders = [
            f"{path.name}: linkedin/{handle}"
            for path, text in _seed_text().items()
            for handle in LINKEDIN.findall(text)
            if not handle.startswith(EXAMPLE_HANDLE_PREFIX)
        ]
        self.assertEqual(offenders, [], "seed corpus links to non-reserved LinkedIn handles")


class SeedAnalysisIdentityTest(unittest.TestCase):
    """The addendum: with every seeded analysis NULL-hashed, three shipped surfaces
    were unreachable on demo data — History's same-CV re-run grouping, the cross-job
    "also analyzed for" linkage, and profile lineage/staleness (a NULL hash is the
    legacy "cannot be judged" value in all three)."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.rows = json.loads((DATA / "seed_analyses" / "analyses.json").read_text(encoding="utf-8"))

    def test_at_least_one_seeded_analysis_carries_a_cv_hash(self) -> None:
        hashed = [r for r in self.rows if r.get("cv_hash")]
        self.assertGreaterEqual(len(hashed), 1, "no seeded analysis carries a cv_hash")

    def test_cv_hashes_are_sha256_shaped_and_distinct_per_candidate(self) -> None:
        hashes = [r["cv_hash"] for r in self.rows if r.get("cv_hash")]
        for value in hashes:
            self.assertRegex(value, r"^[0-9a-f]{64}$")
        self.assertEqual(len(set(hashes)), len(hashes), "two seeded candidates share a cv_hash")

    def test_the_hash_is_derived_from_the_candidate_record(self) -> None:
        """Stable across a re-seed of the same corpus, different when the CV content
        is regenerated — the two properties every consumer of the column relies on."""
        from pipeline.jobfit.seed_analyses import cv_hash_for

        candidates = {
            c["id"]: c
            for c in json.loads((DATA / "seed_candidates" / "candidates.json").read_text(encoding="utf-8"))
        }
        checked = 0
        for row in self.rows:
            record = candidates.get(row["id"])
            if record is None or not row.get("cv_hash"):
                continue
            self.assertEqual(row["cv_hash"], cv_hash_for(record), row["id"])
            mutated = dict(record, displayName=str(record.get("displayName", "")) + " (edited)")
            self.assertNotEqual(row["cv_hash"], cv_hash_for(mutated))
            checked += 1
        self.assertGreater(checked, 0)


class SanitizeLinksTest(unittest.TestCase):
    """The rule is enforced at generation, not just asserted after the fact — a
    prompt is a request, and the corpus is committed."""

    def test_a_plausible_personal_handle_is_moved_into_the_reserved_namespace(self) -> None:
        self.assertEqual(
            sanitize_links({"link": "https://github.com/tmaresova/studyplanner"}),
            {"link": "https://github.com/example-tmaresova/studyplanner"},
        )

    def test_it_is_idempotent(self) -> None:
        once = sanitize_links("https://github.com/tmaresova/x")
        self.assertEqual(sanitize_links(once), once)

    def test_any_other_host_is_replaced_wholesale(self) -> None:
        """Asked for a fictional link, a model hands back a real company page."""
        self.assertEqual(sanitize_links("https://csas.cz/kariera/nabidka"), "https://example.invalid/kariera/nabidka")

    def test_reserved_hosts_pass_through(self) -> None:
        for url in ("https://example.invalid/x", "http://example.com", "https://docs.example.org/a"):
            self.assertEqual(sanitize_links(url), url)

    def test_it_walks_nested_records(self) -> None:
        out = sanitize_links({"evidence": [{"link": "https://gitlab.com/vsykora/thesis"}, {"link": None}]})
        self.assertEqual(out["evidence"][0]["link"], "https://gitlab.com/example-vsykora/thesis")
        self.assertIsNone(out["evidence"][1]["link"])

    def test_non_urls_are_untouched(self) -> None:
        self.assertEqual(sanitize_links("Praha, Czech Republic"), "Praha, Czech Republic")


if __name__ == "__main__":
    unittest.main()
